#!/bin/bash

OUTDIR=$1

if [[ -z ${OUTDIR} ]]; then
	echo "Usage: $0 <out-dir>" >&2
	exit 1
fi

IRC='ircs://irc.libera.chat/#gentoo-python'

irk "${IRC}" - <<<$'\0'

pkgcheck scan -c PythonCompatCheck -R JsonStream > "${OUTDIR}"/pkgcheck-python-compat-update.json
gpy-list-pkg-impls --pkgcheck-output "${OUTDIR}"/pkgcheck-python-compat-update.json > "${OUTDIR}"/python-pkg-impls.txt.new || exit 1
mv "${OUTDIR}"/python-pkg-impls.txt{.new,}
gpy-list-pkg-impls --mirc-color --pkgcheck-output "${OUTDIR}"/pkgcheck-python-compat-update.json > "${OUTDIR}"/python-pkg-impls.irc.new || exit 1
while read -r x; do
	irk "${IRC}" "${x}"
done < <(git diff --no-index -s --word-diff -U0 "${OUTDIR}"/python-pkg-impls.irc{,.new} | tail -n +5 | grep -v '^@@')
mv "${OUTDIR}"/python-pkg-impls.irc{.new,}
