export PACKAGE_MANAGER = pkgcore

PORTDIR ?= $(shell pinspect query get_repo_path gentoo)
timestamp = $(PORTDIR)/metadata/timestamp.commit
# pass via make!
outdir = /dev/null

# Adding new implementations:
# 1. Create rules below & add to upgr_all
# 2. Later, when dot doesn't take too long for it, move to upgr_txt
# 3. Once the impl is stable, move to upgr_base
#
# Please prioritize edges like python-any-r1 consumers to speed up getting
# from 1->2. Especially e.g. git, ninja, meson, doxygen.

# upgrades for impls that are not use.stable.mask-ed
upgr_stable = $(outdir)/312-to-313.txt $(outdir)/313-to-314.txt
# upgrades for impls that are use.stable.mask-ed
upgr_testing =
# upgrades for impls that are use.stable.mask-ed and the graph is too big for dot
upgr_testing_nodot = $(outdir)/314-to-315.txt
# related stabilizations
upgr_streq = $(patsubst %.txt,%-stablereq.txt,$(upgr_stable))
# all upgrade stuff
upgr_txt = $(upgr_stable) $(upgr_streq) $(upgr_testing)
upgr_dot = $(patsubst %.txt,%.dot,$(upgr_txt))
upgr_svg = $(patsubst %.dot,%.svg,$(upgr_dot))
# add new impls here if not stable yet, to avoid insanely huge generation times
upgr_all = $(upgr_txt) $(upgr_dot) $(upgr_svg) $(upgr_testing_nodot)

all = $(upgr_all)

all: $(all) prune-old

prune-old:
	rm -f $(outdir)/39-to-310.* $(outdir)/310-to-311.* $(outdir)/311-to-312.*
	rm -f $(outdir)/pypy*

$(outdir)/314-to-315.txt: $(timestamp)
	mkdir -p $(outdir)
	gpy-upgrade-impl -m python3_14 python3_15 > $@.new
	mv $@.new $@

$(outdir)/314-to-315-stablereq.txt: $(timestamp)
	mkdir -p $(outdir)
	gpy-upgrade-impl -m -s python3_14 python3_15 > $@.new
	mv $@.new $@

$(outdir)/313-to-314.txt: $(timestamp)
	mkdir -p $(outdir)
	gpy-upgrade-impl -m python3_13 python3_14 > $@.new
	mv $@.new $@

$(outdir)/313-to-314-stablereq.txt: $(timestamp)
	mkdir -p $(outdir)
	gpy-upgrade-impl -m -s python3_13 python3_14 > $@.new
	mv $@.new $@

$(outdir)/312-to-313.txt: $(timestamp)
	mkdir -p $(outdir)
	gpy-upgrade-impl -m python3_12 python3_13 > $@.new
	mv $@.new $@

$(outdir)/312-to-313-stablereq.txt: $(timestamp)
	mkdir -p $(outdir)
	gpy-upgrade-impl -m -s python3_12 python3_13 > $@.new
	mv $@.new $@

%.dot: %.txt
	gpy-depgraph -d -m python@gentoo.org $< > $@.new
	mv $@.new $@

%.svg: %.dot
	dot -Tsvg $< > $@.new
	mv $@.new $@

.PHONY: all prune-old
