#!/bin/bash
# Created by Tomáš Chvátal <scarabeus@gentoo.org>
# License WTFPL-2.0

[[ -z $1 ]] && exit 1

if [[ $1 == help || $1 == --help ]]; then
	echo "Usage: $0 herd-or-maintainer-to-checkup"
	exit 0
fi

if [[ $1 = *@* ]]; then
	target="--maintainer=$1"
else
	target="--herd=$1"
fi

#-c pkgcore_checks.imlate \
pushd "$(portageq get_repo_path / gentoo)" > /dev/null
package=$(pquery ${target} --repo=portdir --no-version | tr '\n' ' ')
pcheck -c pkgcore_checks.deprecated \
	-c pkgcore_checks.whitespace \
	-c pkgcore_checks.pkgdir_checks \
	-c pkgcore_checks.metadata_checks \
	-c pkgcore_checks.codingstyle \
	-c pkgcore_checks.visibility \
	-c pkgcore_checks.cleanup \
	${package} \
	--repo=portdir \
	--disable-arches=mips,x86-fbsd,m68k,ppc-macos
popd > /dev/null
